url=https://www.saucedemo.com/
browser=firefox
timeout=10
username=standard_users
password=secret_sauce
loginPage_input_id_username=user-name
loginPage_input_id_password=password
loginPage_button_id_loginButton=login-button
loginPage_title_class_title_Products=title
loginPage_text_error_msg=[data-test='error']